### ISSUE TITLE
SwitchTo.alert Keyword to accept System alert on iOS

### ISSUE THREAD

**Issue by UlhasDeshmukh** [serhatbolsu/robotframework-appiumlibrary#116]
**SwitchTo.alert Keyword to accept System alert on iOS**

is there any Keyword similar to SwitchTo.alert() ?
I'm trying to accept system alert

**Comment by serhatbolsu** [comment]
Did you to just like `click` "Ok" ? We use normal element methods to accept / reject system messages generally.

**Comment by UlhasDeshmukh** [comment]
I cant find xpath to locate this element using appium inspector, 
and not sure if its UIAButton or UIAAlertview to try out click elemnt.

**Comment by serhatbolsu** [comment]
If the alert is notification alert in IOS there can sometimes be a race condition. In iOS in order to interact with it, it should be in the context of application. Sometimes the notification (or any openinng ) alert opens just before the app actually in this case, you can not interact with it. This is an issue of iOS itself (not even Appium). 

What you can do is to use this:
```robotframework
Open Application  ${REMOTE_URL}   autoAcceptAlerts=${True}
```

> note: did not add other "desired Capabilities" intentionally just as an example

Or you can search the disccusion  appium about iOS notification alert

**Comment by UlhasDeshmukh** [comment]
autoAcceptAlerts=${True} was not consistent to close iOS permission alerts ;
hence written custom Python Lib/keyword which does same (i.e. set autoAcceptAlerts to True) and found it very consistent.
```

 desired_caps['autoAcceptAlerts'] = True
 driver = webdriver.Remote(appium_server,
                              desired_caps)
```

**Comment by serhatbolsu** [comment]
The result code is same actually, but if your problem is fixed then it is good, you can re-open the case if you still experience problems

**Comment by ManuBoca92** [comment]
Hi All, I am experiencing the same issue with alerts on iOS. I have tried the suggested autoAcceptAlerts=${True} but this capability does not work on RF and also doesn't work on selenium appium. I have gone through the Appium keyword documentation but I have not been able to find a keyword that performs this task, please help. thanks.
