### ISSUE TITLE
KeyError: 'desired'

### ISSUE THREAD

**Issue by DroiSDK** [serhatbolsu/robotframework-appiumlibrary#141]
The error is raised in _applicationmanagement.py##_get_platform

 platformName = self._current_application().desired_capabilities['desired']['platformName']

In my side, there is no 'desired' key.

fixed when I remove 'desired'

platformName = self._current_application().desired_capabilities['platformName']

---
Appium ver: 1.6
Robotframework: 3.0
Robotframework_AppiumLibrary: 1.4.1

robot test
`Click Element    xpath=//XCUIElementTypeStaticText[@label='${catalog}']`

dump self._current_application().desired_capabilities
```
{'udid': '', 'platformVersion': '9.3', 'app': '/Users/skyer/Documents/projects/droi/DroiBaaSTest-iOS/build/Build/Products/Release-iphonesimulator/DroiBaaSTest-iOS.app', 'platform': 'iOS', 'javascriptEnabled': True, 'automationName': 'XCUITest', 'databaseEnabled': False, 'webStorageEnabled': False, 'browserName': '', 'takesScreenshot': True, 'networkConnectionEnabled': False, 'platformName': 'iOS', 'deviceName': 'iPhone 5s', 'noReset': 'true', 'locationContextEnabled': False}
```

**Comment by slysid** [comment]
I am also facing the same issue and removed and my capabilities doesn't have 'desired'

{u'deviceName': u'Slysid', u'takesScreenshot': True, u'udid': u'9xxxd2xxxxxxxx', u'javascriptEnabled': True, u'app': u'xx.ipa', u'xcodeConfigFile': u'/xcconfig', u'databaseEnabled': False, u'locationContextEnabled': False, u'platform': u'MAC', u'browserName': u'', u'networkConnectionEnabled': False, u'platformVersion': u'10.1', u'webStorageEnabled': False, u'platformName': u'iOS', u'bundleId': u'com.SI'}

**Comment by serhatbolsu** [comment]
@DroiSDK 
I dont understand the issue, what is it that you are trying to achieve ?

**Comment by idxn** [comment]
@serhatbolsu  I think @DroiSDK  means that he tries to make a click on element but get the error because of this line

`platformName = self._current_application().desired_capabilities['desired']['platformName']`

so he checked with 

`self._current_application().desired_capabilities`

and there is no desired key in the desired_capabilities returned.

**Comment by serhatbolsu** [comment]
Well @DroiSDK you are not suppose to use it as python code, instead use the library. So my question is, what is the aim here?
If you like to extend library please take other usages as example

**Comment by idxn** [comment]
@serhatbolsu I don't think he used it via the python code because he mentioned the RBFW version and the RBFW keyword. I haven't tried this myself because I haven't tested the ios10 right now so the new automation XCUITest is out of the league for me. The new appium server 1.6 and automationName=XCUITest might be th cause of problem. It may not returned the same json response as previius version. It's my 2 cents from the log provided though.

**Comment by syedasadulhaq** [comment]
I'm also getting the KeyError: 'desired' error. I've just upgraded to iOS10.11.6, appium1.6. So, yes, it is definitely something with XCUITest

**Comment by serhatbolsu** [comment]
Just submitted a possible fix, please try.

This might not provide a complete compatibility with iOS 10, you are more then welcome to open bugs

**Comment by syedasadulhaq** [comment]
Thank you very much. Seems like it is working. Will check more on Monday.
Have a very nice weekend :)

**Comment by DroiSDK** [comment]
Thanks! Confirmed fixed in iOS test case.
