### ISSUE TITLE
can't use iOSNsPredicateString to find the element

### ISSUE THREAD

**Issue by lalamini** [serhatbolsu/robotframework-appiumlibrary#195]
Hello ,
Would you please provide the location way of iOSNsPredicateString to find the element?
It can improve the efficiency greatly.

**Comment by lalamini** [comment]
I had added some code to appium-library to finish iOSNsPredicateString location
I did several test to compare xpath and iOSNsPredicateString, the way use iOSNsPredicateString just take half time of the way use xpath.
Can I contribute my code to your project?
Here is my test data: 
    20171101 17:10:14.229 :  INFO : Clicking element 'xpath=//XCUIElementTypeButton[@name="AAA"]'.
    20171101 17:10:21.255 :  INFO : Slept 2 seconds
    time elaspe 5.026

    20171101 17:12:38.893 :  INFO : Clicking element 'xpath=//XCUIElementTypeButton[@name="AAA"]'.
    20171101 17:12:45.920 :  INFO : Slept 2 seconds
    time elaspe 7.27

    20171101 17:13:33.539 :  INFO : Clicking element 'xpath=//XCUIElementTypeButton[@name="AAA"]'.
    20171101 17:13:40.505 :  INFO : Slept 2 seconds
    time elaspe 6.966

    20171101 17:14:38.821 :  INFO : Clicking element 'xpath=//XCUIElementTypeButton[@name="AAA"]'.
    20171101 17:14:45.860 :  INFO : Slept 2 seconds
    time elaspe 7.39

    20171101 17:16:45.267 :  INFO : Clicking element 'xpath=//XCUIElementTypeButton[@name="AAA"]'.
    20171101 17:16:52.336 :  INFO : Slept 2 seconds
    time elaspe 7.69

    20171101 17:20:53.652 :  INFO : Clicking element 'nsp=type=="XCUIElementTypeButton" AND name=="AAA"'.
    20171101 17:20:57.134 :  INFO : Slept 2 seconds
    time elaspe 3.482


    20171101 17:21:56.650 :  INFO : Clicking element 'nsp=type=="XCUIElementTypeButton" AND name=="AAA"'.
    20171101 17:22:00.162 :  INFO : Slept 2 seconds
    time elaspe 3.512

    20171101 17:23:39.378 :  INFO : Clicking element 'nsp=type=="XCUIElementTypeButton" AND name=="AAA"'.
    20171101 17:23:42.946 :  INFO : Slept 2 seconds
    time elaspe 2.568

    20171101 17:24:45.724 :  INFO : Clicking element 'nsp=type=="XCUIElementTypeButton" AND name=="AAA"'.
    20171101 17:24:49.206 :  INFO : Slept 2 seconds
    time elaspe 3.482

**Comment by vickywyy** [comment]
@lalamini 
    could you share your updated appiumLibrary with nsp locator here?
    thanks!

**Comment by lalamini** [comment]
Hello vickywyy,

Sorry to reply so late

I have done a pull request at this project

You can get the information about it at "add iOSNsPredicate location to elementfinder #196"

It's easy to make it available because just one file was changed.


I hope all people can use the nsp locator as soon as possible!


Thanks!


________________________________
发件人: vickywyy <notifications@github.com>
发送时间: 2018年3月6日 15:41
收件人: serhatbolsu/robotframework-appiumlibrary
抄送: lalamini; Mention
主题: Re: [serhatbolsu/robotframework-appiumlibrary] can't use iOSNsPredicateString to find the element (#195)


@lalamini<https://github.com/lalamini>
could you share your updated appiumLibrary with nsp locator here?
thanks!

―

**Comment by Kitty2014** [comment]
any demo or this fix  coming release？ @lalamini  @vickywyy   Thanks！

**Comment by lalamini** [comment]
you can check my pull request，if you don’t want to pull my rep, you can just change one file according to my commit log , it’s easy, you can try it, iOSNs... location can reduce at least half time, it worth trying.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Kitty2014** [comment]
such chain locator much faster and easy for us, could help check  how to integrated find_element_by_ios_class_chain

**/XCUIElementTypeButton[`name CONTAINS[cd] ' 价格最'`]
**/XCUIElementTypeButton[`name IN {'baisegouwuche','naviAppointListWhite','naviAppointList'}`]

**Comment by lalamini** [comment]
I don't know ,you can try it , if it works ,please let me know.
If it can't work, also let me know , I will try to resolve it!
________________________________
发件人: Kitty2014 <notifications@github.com>
发送时间: 2018年7月5日 16:16
收件人: serhatbolsu/robotframework-appiumlibrary
抄送: lalamini; Mention
主题: Re: [serhatbolsu/robotframework-appiumlibrary] can't use iOSNsPredicateString to find the element (#195)


such chain locator much faster and easy for us, could help check how to integrated find_element_by_ios_class_chain

**/XCUIElementTypeButton[name CONTAINS[cd] ' 价格最']
**/XCUIElementTypeButton[name IN {'baisegouwuche','naviAppointListWhite','naviAppointList'}]

―

**Comment by Kitty2014** [comment]
@lalamini Hi , try  nsp works,  but chain fail  since RED  Robo seems does not get the value which return from server::::
I  attached the revised document
![ob j1](https://user-images.githubusercontent.com/7512412/42314986-e1b16164-8078-11e8-998f-8958cd8ebabc.png)
![ob j2](https://user-images.githubusercontent.com/7512412/42314998-e9dfe770-8078-11e8-876c-04d11e0559e7.png)
![obj3](https://user-images.githubusercontent.com/7512412/42315028-f7d178c6-8078-11e8-9889-1ca8678ecc5a.png)
![obj4](https://user-images.githubusercontent.com/7512412/42315037-ff12f06a-8078-11e8-9c6d-324944c277e0.png)
![bj5](https://user-images.githubusercontent.com/7512412/42315044-024373ea-8079-11e8-83e9-1cf7a7a731cf.png)




"value":{"ELEMENT":
Locator:
chain=**/*[`name IN {'车龄','排放标准'}`]

2018-07-05 08:45:29:930 - [HTTP] --> POST /wd/hub/session/74a6948c-3b17-44b9-b763-451753fd1d15/element
2018-07-05 08:45:29:930 - [HTTP] {"using":"-ios class chain","sessionId":"74a6948c-3b17-44b9-b763-451753fd1d15","value":"**/*[`name IN {'车龄','排放标准'}`]"}
2018-07-05 08:45:29:930 - [debug] [W3C] Calling AppiumDriver.findElement() with args: ["-ios class chain","**/*[`name IN {'车龄','排放标准'}`]","74a6948c-3b17-44b9-b763-451753fd1d15"]
2018-07-05 08:45:29:930 - [debug] [XCUITest] Executing command 'findElement'
2018-07-05 08:45:29:930 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2018-07-05 08:45:29:931 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-07-05 08:45:29:932 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/F2D854CA-D3CC-40AD-8F62-CF3997ED9F21/element] with body: {"using":"class chain","value":"**/*[`name IN {'车龄','排放标准'}`]"}
2018-07-05 08:45:30:509 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"5B020000-0000-0000-F501-000000000000"},"sessionId":"F2D854CA-D3CC-40AD-8F62-CF3997ED9F21","status":0}
2018-07-05 08:45:30:509 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5B020000-0000-0000-F501-000000000000"}
2018-07-05 08:45:30:510 - [HTTP] <-- POST /wd/hub/session/74a6948c-3b17-44b9-b763-451753fd1d15/element 200 580 ms - 122
2018-07-05 08:45:30:510 - [HTTP] 
2018-07-05 08:45:30:514 - [HTTP] --> GET /wd/hub/session/74a6948c-3b17-44b9-b763-451753fd1d15/screenshot
2018-07-05 08:45:30:515 - [HTTP] {}
2018-07-05 08:45:30:515 - [debug] [W3C] Calling AppiumDriver.getScreenshot() with args: ["74a6948c-3b17-44b9-b763-451753fd1d15"]
2018-07-05 08:45:30:515 - [debug] [XCUITest] Executing command 'getScreenshot'
2018-07-05 08:45:30:515 - [debug] [XCUITest] Taking screenshot with WDA
2018-07-05 08:45:30:516 - [debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F2D854CA-D3CC-40AD-8F62-CF3997ED9F21/screenshot] with no body
2018-07-05 08:45:30:721 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"


20180705 17:20:52.786 : FAIL : ValueError: Element locator 'chain=**/*[`name CONTAINS[cd] '辆车'`]' did not match any elements.
20180705 17:20:57.790 : INFO : Clicking element 'chain=**/*[`name CONTAINS[cd] '辆车'`]'.



20180705 17:07:53.296 : INFO : Element 'xpath=//XCUIElementTypeButton[@name='筛选 ']' attribute 'name' value '筛选 ' 
20180705 17:07:53.296 : INFO : ${元素name} = 筛选 
20180705 17:07:53.298 : INFO : 筛选 
20180705 17:07:53.299 : INFO : Clicking element 'xpath=//XCUIElementTypeButton[@name='筛选 ']'.
20180705 17:07:55.400 : INFO : Clicking element 'nsp=type=='XCUIElementTypeStaticText' AND name=='颜色' AND visible==1'.
20180705 17:07:57.852 : INFO : Clicking element 'chain=**/*[`name IN {'车龄','排放标准'}`]'.
20180705 17:07:58.074 : INFO : </td></tr><tr><td colspan="3"><a href=" ">< img src="appium-screenshot-1.png" width="800px"></a >
20180705 17:07:58.082 : FAIL : AttributeError: 'WebDriver' object has no attribute 'find_element_by_ios_class_chain

**Comment by Kitty2014** [comment]
attached the  change file elementfinder.py
'chain': self._find_by_chain,
def _find_by_chain(self, browser, criteria, tag, constraints):
        """Find element matches by  iOSChainString."""
        return self._filter_elements(
            browser.find_element_by_ios_class_chain(criteria),
            tag, constraints)

[elementfinder.py.zip](https://github.com/serhatbolsu/robotframework-appiumlibrary/files/2165942/elementfinder.py.zip)

**Comment by Kitty2014** [comment]
@lalamini  can you  update?Thanks

**Comment by lalamini** [comment]
I am not very familiar with ios class chain， But   I am sure it can be located by appium
<img width="814" alt="2018-07-09 4 10 38" src="https://user-images.githubusercontent.com/9879768/42438595-03a891da-8393-11e8-8942-d7637556c661.png">
It reported NoSuchElementException not like you
I show you how to add them 
add 
` 'chain': self._find_by_class_chain,  `
to __init__ (self)   like 'nsp'  as you know
add
`def _find_by_class_chain(self, browser, criteria, tag, constraints):
        """Find element matches by iOS class chain """
        return self._filter_elements(
            browser.find_element_by_ios_class_chain(criteria),
            tag, constraints)`

after function 
`def _find_by_nsp(self, browser, criteria, tag, constraints): ...`

Then enjoy it

but anyway , I found class chain can't support the locater way as you show, such as 'chain=/*[name CONTAINS[cd] '辆车']'

you can refer to this:
https://github.com/appium/appium-xcuitest-driver/pull/391
**The class chain query type is similar to xpath, but can only include indexes and valid class names.**
if you want to use CONTAINS function, you can use like this:
nsp=name MATCHES "辆车" 
It will work as grep function, may be match your requirement!   :-)

**Comment by lalamini** [comment]
I have checked your code , the same as me.
Maybe you should upgrade you appiumlibrary.

**Comment by Kitty2014** [comment]
@lalamini   Thanks for you replay,
[elementfinder.py.zip](https://github.com/serhatbolsu/robotframework-appiumlibrary/files/2175507/elementfinder.py.zip)
 same with the attachment?

**Comment by lalamini** [comment]
def _find_by_chain(self, browser, criteria, tag, constraints):
        """Find element matches by  iOSChainString."""
        return self._filter_elements(
            browser.find_element_by_ios_class_chain(criteria),
            tag, constraints)

should be

    def _find_by_chain(self, browser, criteria, tag, constraints):
        """Find element matches by  iOSChainString."""
        return self._filter_elements(
            browser.find_elements_by_ios_class_chain(criteria),
            tag, constraints)

:-)
________________________________
发件人: Kitty2014 <notifications@github.com>
发送时间: 2018年7月9日 17:28
收件人: serhatbolsu/robotframework-appiumlibrary
抄送: lalamini; Mention
主题: Re: [serhatbolsu/robotframework-appiumlibrary] can't use iOSNsPredicateString to find the element (#195)


@lalamini<https://github.com/lalamini> Thanks for you replay,
elementfinder.py.zip<https://github.com/serhatbolsu/robotframework-appiumlibrary/files/2175507/elementfinder.py.zip>
same with the attachment?

―

**Comment by cplus02** [comment]
Hi, I installed AppiumLibrary 1.4.6 but found I can't use nsp locator strategy, did I miss anything?

**Comment by lalamini** [comment]
yes，you miss something，the owner has merged the nsp commit to the master branch, you can check it

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cplus02** [comment]
Thanks, I found the file and copy it into my appiumlibrary now it works well :-)

**Comment by shenjianyun** [comment]
@lalamini , i use RF+appium, if there are more than one element like xpath=//XCUIElementTypeButton[@name="AAA"], in xpath can use index or position() to locate the second element, but in iOSNsPredicate, how to do this? i encoutering this situation and i don't know  what i can do, please give me some help, thanks

**Comment by serhatbolsu** [comment]
nspredicate is supported now
