### ISSUE TITLE
Compatibility issue wirth selenium package

### ISSUE THREAD

**Issue by axiom41** [serhatbolsu/robotframework-appiumlibrary#350]
Hello. Installing the latest rpaframework, the selenium package has been automatically updated to 4.4.3, that is marked as not compatible with robotframework-appiumlibrary==1.6.3

The reported message is:

**robotframework-appiumlibrary 1.6.3 requires selenium<4,>=2.47.1, but you have selenium 4.4.3 which is incompatible.**

Would it be possible to have a new version of robotframework-appiumlibrary, that has not been updated since Dec 2021?

Thanks

**Comment by filipehba** [comment]
this issue was fixed in this commit [d0a518d](https://github.com/serhatbolsu/robotframework-appiumlibrary/commit/d0a518d0216a0e22561d5ba8fe68889863caae08), but a new release is not published.

in this thread there is a solution https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/337#issuecomment-1098943131

**Comment by chrcht** [comment]
@serhatbolsu is it possible to release 1.6.4 based on master, where this problem is solved?

**Comment by serhatbolsu** [comment]
I have update the library to at least being able to run while selenium4 is installed however still needs to fix some keywords
